# create a kbc game 


print("WELCOME TO KBC GAME!!!") 
print("QUESTION 1   -  RS 1000")
print("QUESTION 2   -  RS 4000")
print("QUESTION 3   -  RS 10000")
print("QUESTION 4   -  RS 20000")
print("QUESTION 5   -  RS 35000")
print("QUESTION 6   -  RS 130000")
print("QUESTION 7   -  RS 180000")
print("QUESTION 8   -  RS 250000")
print("QUESTION 9   -  RS 450000")
print("QUESTION 10  -  RS 70000000")
ans=[1,2,3,4]
sum=0
j=1;i=1
counter = False
while(i>0):
    while(j>0):
        print("                         ")
        print("QUESTION 1 ON YOUR SCREEN")
        print("                         ")
        print(" Current Railway Minister of India is ")
        print("                         ")
        print(" 1) MAMTA BANARJEE                           2) RAM VILASH ")
        print(" 3) ASHWINI VASHNAV                          4) PIYUSH GOYAL")

        ans1=input(print( " enter your answer\n " ))
        if(int(ans1)==ans[2]):
            print("you have won rupess 1000")                           
            sum=sum+1000
            if(j==1):
                j=j+1 
                counter=True          
                break
        else:
             
             break
    
    if(counter==True):
       
        counter=False
        print("                         ")
        print("QUESTION 2 ON YOUR SCREEN")
        print("                         ")
        print(" Ranthambore, Sariska and Keoladeo Ghana are all names of what? ")
        print("                         ")
        print(" 1) NATIONAL PARKS                             2) MOUNTAINS")
        print(" 3) RIVERS                                     4) CITIES"   )
        print("                         ")
        ans2=input(print("enter your answer"))
        if(int(ans2)==ans[0]):
            print("you have won 4000 rupees")
            sum=sum+4000
            if(j==2):
                j=j+1
                counter=True  
                
        else:
            
            break
                
    if(counter==True):
       
            counter=False
            print("                         ")
            print("QUESTION 3 ON YOUR SCREEN")
            print("                         ")
            print(" In 2020, Louise Gluck won the Nobel Prize in which category? ")
            print("                         ")
            print(" 1) LITERATURE                             2) MUSIC ")
            print(" 3) SPORTS                                 4) PEACE ")
            print("                         ")
            ans3=input(print("enter your answer"))
            if(int(ans3)==ans[0]):
                print("you have won 10000 rupees")
                sum=sum+10000
                if(j==3):
                    j=j+1
                    counter=True
                    
                
            else:
                break

    if(counter==True):
        counter=False
        print("                         ")
        print("QUESTION 4 ON YOUR SCREEN")
        print("                         ")
        print(" In terms of production, which of these is the largest train coach manufacturing unit in the world? ")
        print("                         ")
        print(" 1) BANGLORE                                      2) MUMBAI ")
        print(" 3) KOLKATA                                       4) CHENNAI")
        print("                         ")
        ans4=input(print(" enter your choice "))
        if(int(ans4)==ans[3]):
            print("you have won 20000 rupees")
            sum=sum+20000
            if(j==4):
                j=j+1
                counter=True
             
            else:
                break

    if(counter==True):
        counter=False
        print("                         ")
        print("QUESTION 5 ON YOUR SCREEN")
        print("                         ")
        print("Which of the following companies was originally started as a loom manufacturing unit in 1909?")
        print("                         ")
        print(" 1) HONDA                                            2) SUZUKI")
        print(" 3) MERCEDES                                         4) CEAT")
        print("                         ")
        ans5=input(print(" enter your choice"))
        if(int(ans5)==ans[1]):
            print("you have won 35000 rupees" )
            sum=sum+35000
            if(j==5):
                j=j+1
                counter=True
            else:
                break

    if(counter==True):
        counter=False
        print("                         ")
        print("                         ")
        print("QUESTION 6 ON YOUR SCREEN")
        print("                         ")
        print("Which of these colors when mixed with red will produce the color orange?")
        print("                         ")
        print(" 1) VOILET                                    2) RED")
        print(" 3) ORANGE                                    4) YELLOW ")
        print("                         ")
        ans6=input(print(" enter your choice"))
        if(int(ans6)==ans[3]):
            print("you have won 1300000 rupees" )
            sum=sum+1300000
            if(j==6):
                j=j+1
                counter=True
            else:
                break
   
   
    if(counter==True):
        counter=False
        print("                         ")
        print("QUESTION 7 ON YOUR SCREEN")
        print("                         ")
        print("In November 2020 Indian-origin Priyanca Radhakrishnan became a minister in which country?")
        print("                         ")
        print(" 1) NEWZEALAND                                     2) THAILAND")
        print(" 3) SRILANKA                                       4) UK")
        print("                         ")
        ans7=input(print(" enter your choice"))
        if(int(ans7)==ans[0]):
            print("you have won 1800000 rupees" )
            sum=sum+1800000
            if(j==7):
                j=j+1
                counter=True
            else:
                break
   
   
    if(counter==True):
        counter=False
        print("                         ")
        print("QUESTION 8 ON YOUR SCREEN")
        print("                         ")
        print(" Who was the Defense Minister of India when the India-China War of 1962 began?")
        print("                         ")
        print(" 1) RAJNATH SINGH                                        2) VK KRISHNAN MENON ")
        print(" 3) JAGJIVAN RAM                                         4) NIRMALA SITARAMAN ")
        print("                         ")
        ans8=input(print(" enter your choice"))
        if(int(ans8)==ans[1]):
            print("you have won 2500000 rupees" )
            sum=sum+2500000
            if(j==8):
                j=j+1
                counter=True
            else:
                break

    
    if(counter==True):
        counter=False
        print("                         ")
        print("QUESTION 9 ON YOUR SCREEN")
        print("                         ")
        print(" Which two countries share the longest international land border?")
        print("                         ")
        print(" 1) RUSSIA-KAZAKASTAN                                 2) ARGENTINA-CHILE ")
        print(" 3) USA-CANADA                                        4) MONGOLIA-CHINA")
        print("                         ")
        ans9=input(print(" enter your choice"))
        if(int(ans9)==ans[2]):
            print("you have won 4500000 rupees" )
            sum=sum+4500000
            if(j==9):
                j=j+1
                counter=True
            else:
                break
        
   
    if(counter==True):
        counter=False
        print("                         ")
        print("QUESTION 10 ON YOUR SCREEN")
        print("                         ")
        print(" Patna was renamed Azimabad in 1704 after Azim-us-Shan was the grandson of which Mughal emperor?")
        print("                         ")
        print(" 1) AZARUDDIN                                  2) AZIM PATHAN  ")
        print(" 3) MOHAMED HASNAN                             4) AURANGZEB ")
        print("                         ")
        ans10=input(print(" enter your choice"))
        if(int(ans10)==ans[3]):
            print("you have won 10000000 rupees" )
            sum=sum+10000000
            if(j==10):
                j=j+1
                counter=True
                break
            else:
                break
    else:
        break

print("you have lost!!!")
print("your total winning is ", sum)



